config/routes.rb
Rails.application.routes.draw do
  
  resources :modalities
  resources :concerted_qualifications
  resources :concept_payments
  resources :installations
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  devise_for :users, controllers: {sessions: 'user/sessions', registrations: 'user/registrations'}
  root to: 'welcome#index'
  #RESOURCE
  resources :schedules
  resources :time_tables
  resources :type_scolarships
  resources :scolarships
  resources :graduation_institutions
  resources :emergency_contacts
  resources :study_plans
  resources :asignatures
  resources :students, path: "estudiantes"
  resources :departments
  resources :session_modules
  resources :tuitions
  resources :costs
  resources :workplaces
  resources :education_levels
  resources :level_studies
  resources :teachers, :path =>'profesores'
  resources :addresses, :path =>'direcciones'
  resources :level_academics, :path =>'niveles/academicos'
  resources :type_activities, :path =>'tipos/actividad'
  resources :type_costs, :path =>'tipos/costo'
  resources :pay_concepts, :path => 'conceptos/pago'
  resources :type_payments, :path => 'tipos/pago'
  resources :ingresses, :path =>'ingresos'
  resources :cycles, :path =>'ciclos'
  resources :debits, :path =>'adeudos'
  resources :activities, :path =>'actividades'
  resources :module_activities, :path =>'modulos/actividades'
  resources :administrators
  resources :assistants, :path => 'asistentes'
  #GET
  #get '/reporte/alumno', to: 'reports#students'
  get '/registrar', to: 'user#new_user'
  get '/ver/adeudos/actividades/', to: 'debits#get_user_debits', as: 'show_debits'
  get '/usuarios', to: 'user#get_users'
  get '/actividad/registro', to: 'register_user_activity#index' , as: 'register'
  get '/actividad/lista', to: 'register_user_activity#get_activity'
  post '/actividad/registrar/usuario', to: 'register_user_activity#saveUserInActivity'
  post '/pagar/adeudo', to: 'ingresses#add' 
  get '/reporte/inscrito/actividad/:id', to: 'reports#payment_report', as: 'recibo'
  get '/reporte/actividad/:id/inscritos', to: 'reports#assistants_activity_report', as: 'inscritos'
  get '/constancias/actividades/:id', to: 'reports#constancy_ac'
  post '/cargar/materias', to: 'asignatures#charge_asignatures_from_file'
  #POST
  post "/graphql", to: "graphql#execute"
  post '/registrar', to: 'user#create_user'
  post '/docente/documentos/:type', to: 'teachers#upload_files'
  post '/docente/registro/', to: 'teachers#create'
  patch '/docente/actualizar/', to: 'teachers#update'
  get '/reporte/ingresos/:id', to: 'reports#ingress_activity_report'
  get '/reporte/inscripcion/:id', to: 'reports#inscription_report'
  get '/formato/concentrado/:id', to: 'formats#grade_sheets'
  get '/formato/asistencia/:id', to: 'formats#assistant_sheets'
  get '/formato/tira/materias/:id', to: 'formats#schedule_assignment'
  get '/formato/compromiso/pagos/:id', to: 'formats#commitment_payment'
  get '/profesor/:id', to: 'teachers#get_teacher'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/type_scolarship.rb
class TypeScolarship < ApplicationRecord
    has_many :scolarships

    validates :name,
    presence: {message: "es requerido"}  
end

app/controllers/type_scolarships_controller.rb
class TypeScolarshipsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_type_scolarship, only: [:show, :edit, :update, :destroy]

  # GET /type_scolarships
  # GET /type_scolarships.json
  def index
    @type_scolarships = TypeScolarship.all
  end

  # GET /type_scolarships/1
  # GET /type_scolarships/1.json
  def show
  end

  # GET /type_scolarships/new
  def new
    @type_scolarship = TypeScolarship.new
  end

  # GET /type_scolarships/1/edit
  def edit
  end

  # POST /type_scolarships
  # POST /type_scolarships.json
  def create
    @type_scolarship = TypeScolarship.new(type_scolarship_params)

    if @type_scolarship.save
      render json: {data: @type_scolarship, status:'200', msg: 'El tipo de beca se creó correctamente'}
    else
      render json: {data: nil, status:'500', msg:  @type_scolarship.errors.full_messages}
    end
  end

  # PATCH/PUT /type_scolarships/1
  # PATCH/PUT /type_scolarships/1.json
  def update
    if @type_scolarship.update(type_scolarship_params)
      render json: {data: @type_scolarship, status:'200', msg: 'El tipo de beca se actualizó correctamente'}
    else
      render json: {data: nil, status:'500', msg:  @type_scolarship.errors.full_messages}
    end
  end

  # DELETE /type_scolarships/1
  # DELETE /type_scolarships/1.json
  def destroy
    if @type_scolarship.update(status: 0)
      render json: {data: nil, status:'200', msg: 'El tipo de beca se eliminó correctamente'}
    else
      render json: {data: nil, status:'500', msg:  @type_scolarship.errors.full_messages}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_scolarship
      @type_scolarship = TypeScolarship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_scolarship_params
      params.require(:type_scolarship).permit(:name, :status)
    end
end

app/helpers/type_scolarships_helper.rb
module TypeScolarshipsHelper
end

app/views/type_scolarships/_form.html.erb
<%= form_with(model: type_scolarship, local: true) do |form| %>
  <% if type_scolarship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type_scolarship.errors.count, "error") %> prohibited this type_scolarship from being saved:</h2>

      <ul>
      <% type_scolarship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/type_scolarships/edit.html.erb
<h1>Editing Type Scolarship</h1>

<%= render 'form', type_scolarship: @type_scolarship %>

<%= link_to 'Show', @type_scolarship %> |
<%= link_to 'Back', type_scolarships_path %>

app/views/type_scolarships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Type Scolarships</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @type_scolarships.each do |type_scolarship| %>
      <tr>
        <td><%= type_scolarship.name %></td>
        <td><%= type_scolarship.status %></td>
        <td><%= link_to 'Show', type_scolarship %></td>
        <td><%= link_to 'Edit', edit_type_scolarship_path(type_scolarship) %></td>
        <td><%= link_to 'Destroy', type_scolarship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type Scolarship', new_type_scolarship_path %>

app/views/type_scolarships/new.html.erb
<h1>New Type Scolarship</h1>

<%= render 'form', type_scolarship: @type_scolarship %>

<%= link_to 'Back', type_scolarships_path %>

app/views/type_scolarships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type_scolarship.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @type_scolarship.status %>
</p>

<%= link_to 'Edit', edit_type_scolarship_path(@type_scolarship) %> |
<%= link_to 'Back', type_scolarships_path %>