config/routes.rb
Rails.application.routes.draw do
  
  resources :modalities
  resources :concerted_qualifications
  resources :concept_payments
  resources :installations
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  devise_for :users, controllers: {sessions: 'user/sessions', registrations: 'user/registrations'}
  root to: 'welcome#index'
  #RESOURCE
  resources :schedules
  resources :time_tables
  resources :type_scolarships
  resources :scolarships
  resources :graduation_institutions
  resources :emergency_contacts
  resources :study_plans
  resources :asignatures
  resources :students, path: "estudiantes"
  resources :departments
  resources :session_modules
  resources :tuitions
  resources :costs
  resources :workplaces
  resources :education_levels
  resources :level_studies
  resources :teachers, :path =>'profesores'
  resources :addresses, :path =>'direcciones'
  resources :level_academics, :path =>'niveles/academicos'
  resources :type_activities, :path =>'tipos/actividad'
  resources :type_costs, :path =>'tipos/costo'
  resources :pay_concepts, :path => 'conceptos/pago'
  resources :type_payments, :path => 'tipos/pago'
  resources :ingresses, :path =>'ingresos'
  resources :cycles, :path =>'ciclos'
  resources :debits, :path =>'adeudos'
  resources :activities, :path =>'actividades'
  resources :module_activities, :path =>'modulos/actividades'
  resources :administrators
  resources :assistants, :path => 'asistentes'
  #GET
  #get '/reporte/alumno', to: 'reports#students'
  get '/registrar', to: 'user#new_user'
  get '/ver/adeudos/actividades/', to: 'debits#get_user_debits', as: 'show_debits'
  get '/usuarios', to: 'user#get_users'
  get '/actividad/registro', to: 'register_user_activity#index' , as: 'register'
  get '/actividad/lista', to: 'register_user_activity#get_activity'
  post '/actividad/registrar/usuario', to: 'register_user_activity#saveUserInActivity'
  post '/pagar/adeudo', to: 'ingresses#add' 
  get '/reporte/inscrito/actividad/:id', to: 'reports#payment_report', as: 'recibo'
  get '/reporte/actividad/:id/inscritos', to: 'reports#assistants_activity_report', as: 'inscritos'
  get '/constancias/actividades/:id', to: 'reports#constancy_ac'
  post '/cargar/materias', to: 'asignatures#charge_asignatures_from_file'
  #POST
  post "/graphql", to: "graphql#execute"
  post '/registrar', to: 'user#create_user'
  post '/docente/documentos/:type', to: 'teachers#upload_files'
  post '/docente/registro/', to: 'teachers#create'
  patch '/docente/actualizar/', to: 'teachers#update'
  get '/reporte/ingresos/:id', to: 'reports#ingress_activity_report'
  get '/reporte/inscripcion/:id', to: 'reports#inscription_report'
  get '/formato/concentrado/:id', to: 'formats#grade_sheets'
  get '/formato/asistencia/:id', to: 'formats#assistant_sheets'
  get '/formato/tira/materias/:id', to: 'formats#schedule_assignment'
  get '/formato/compromiso/pagos/:id', to: 'formats#commitment_payment'
  get '/profesor/:id', to: 'teachers#get_teacher'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cost.rb
class Cost < ApplicationRecord
    belongs_to :level_academic
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(cost_params)

    respond_to do |format|
      if @cost.save
        format.html { redirect_to @cost, notice: 'Cost was successfully created.' }
        format.json { render :show, status: :created, location: @cost }
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:inscription_lic, :inscription_master, :reinscription_lic, :reinscription_master, :tuition_lic, :tuition_master)
    end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_form.html.erb
<%= form_with(model: cost, local: true) do |form| %>
  <% if cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
      <% cost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :inscription_lic %>
    <%= form.text_field :inscription_lic %>
  </div>

  <div class="field">
    <%= form.label :inscription_master %>
    <%= form.text_field :inscription_master %>
  </div>

  <div class="field">
    <%= form.label :reinscription_lic %>
    <%= form.text_field :reinscription_lic %>
  </div>

  <div class="field">
    <%= form.label :reinscription_master %>
    <%= form.text_field :reinscription_master %>
  </div>

  <div class="field">
    <%= form.label :tuition_lic %>
    <%= form.text_field :tuition_lic %>
  </div>

  <div class="field">
    <%= form.label :tuition_master %>
    <%= form.text_field :tuition_master %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/costs/edit.html.erb
<h1>Editing Cost</h1>

<%= render 'form', cost: @cost %>

<%= link_to 'Show', @cost %> |
<%= link_to 'Back', costs_path %>

app/views/costs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Costs</h1>

<table>
  <thead>
    <tr>
      <th>Inscription lic</th>
      <th>Inscription master</th>
      <th>Reinscription lic</th>
      <th>Reinscription master</th>
      <th>Tuition lic</th>
      <th>Tuition master</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @costs.each do |cost| %>
      <tr>
        <td><%= cost.inscription_lic %></td>
        <td><%= cost.inscription_master %></td>
        <td><%= cost.reinscription_lic %></td>
        <td><%= cost.reinscription_master %></td>
        <td><%= cost.tuition_lic %></td>
        <td><%= cost.tuition_master %></td>
        <td><%= link_to 'Show', cost %></td>
        <td><%= link_to 'Edit', edit_cost_path(cost) %></td>
        <td><%= link_to 'Destroy', cost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cost', new_cost_path %>

app/views/costs/new.html.erb
<h1>New Cost</h1>

<%= render 'form', cost: @cost %>

<%= link_to 'Back', costs_path %>

app/views/costs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Inscription lic:</strong>
  <%= @cost.inscription_lic %>
</p>

<p>
  <strong>Inscription master:</strong>
  <%= @cost.inscription_master %>
</p>

<p>
  <strong>Reinscription lic:</strong>
  <%= @cost.reinscription_lic %>
</p>

<p>
  <strong>Reinscription master:</strong>
  <%= @cost.reinscription_master %>
</p>

<p>
  <strong>Tuition lic:</strong>
  <%= @cost.tuition_lic %>
</p>

<p>
  <strong>Tuition master:</strong>
  <%= @cost.tuition_master %>
</p>

<%= link_to 'Edit', edit_cost_path(@cost) %> |
<%= link_to 'Back', costs_path %>