config/routes.rb
Rails.application.routes.draw do
  
  resources :modalities
  resources :concerted_qualifications
  resources :concept_payments
  resources :installations
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  devise_for :users, controllers: {sessions: 'user/sessions', registrations: 'user/registrations'}
  root to: 'welcome#index'
  #RESOURCE
  resources :schedules
  resources :time_tables
  resources :type_scolarships
  resources :scolarships
  resources :graduation_institutions
  resources :emergency_contacts
  resources :study_plans
  resources :asignatures
  resources :students, path: "estudiantes"
  resources :departments
  resources :session_modules
  resources :tuitions
  resources :costs
  resources :workplaces
  resources :education_levels
  resources :level_studies
  resources :teachers, :path =>'profesores'
  resources :addresses, :path =>'direcciones'
  resources :level_academics, :path =>'niveles/academicos'
  resources :type_activities, :path =>'tipos/actividad'
  resources :type_costs, :path =>'tipos/costo'
  resources :pay_concepts, :path => 'conceptos/pago'
  resources :type_payments, :path => 'tipos/pago'
  resources :ingresses, :path =>'ingresos'
  resources :cycles, :path =>'ciclos'
  resources :debits, :path =>'adeudos'
  resources :activities, :path =>'actividades'
  resources :module_activities, :path =>'modulos/actividades'
  resources :administrators
  resources :assistants, :path => 'asistentes'
  #GET
  #get '/reporte/alumno', to: 'reports#students'
  get '/registrar', to: 'user#new_user'
  get '/ver/adeudos/actividades/', to: 'debits#get_user_debits', as: 'show_debits'
  get '/usuarios', to: 'user#get_users'
  get '/actividad/registro', to: 'register_user_activity#index' , as: 'register'
  get '/actividad/lista', to: 'register_user_activity#get_activity'
  post '/actividad/registrar/usuario', to: 'register_user_activity#saveUserInActivity'
  post '/pagar/adeudo', to: 'ingresses#add' 
  get '/reporte/inscrito/actividad/:id', to: 'reports#payment_report', as: 'recibo'
  get '/reporte/actividad/:id/inscritos', to: 'reports#assistants_activity_report', as: 'inscritos'
  get '/constancias/actividades/:id', to: 'reports#constancy_ac'
  post '/cargar/materias', to: 'asignatures#charge_asignatures_from_file'
  #POST
  post "/graphql", to: "graphql#execute"
  post '/registrar', to: 'user#create_user'
  post '/docente/documentos/:type', to: 'teachers#upload_files'
  post '/docente/registro/', to: 'teachers#create'
  patch '/docente/actualizar/', to: 'teachers#update'
  get '/reporte/ingresos/:id', to: 'reports#ingress_activity_report'
  get '/reporte/inscripcion/:id', to: 'reports#inscription_report'
  get '/formato/concentrado/:id', to: 'formats#grade_sheets'
  get '/formato/asistencia/:id', to: 'formats#assistant_sheets'
  get '/formato/tira/materias/:id', to: 'formats#schedule_assignment'
  get '/formato/compromiso/pagos/:id', to: 'formats#commitment_payment'
  get '/profesor/:id', to: 'teachers#get_teacher'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/emergency_contact.rb
class EmergencyContact < ApplicationRecord
    belongs_to :student

    validates :name, 
        presence: { message: "es requerido" }
    validates :cell_phone,
        presence: {message: "es requerida"}
    validates :telephone,
        presence: {message: "es requerida"}
    validates :student_id,
        presence: {message: "es requerido"}
end

app/controllers/emergency_contacts_controller.rb
class EmergencyContactsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_emergency_contact, only: [:show, :edit, :update, :destroy]

  # GET /emergency_contacts
  # GET /emergency_contacts.json
  def index
    @emergency_contacts = EmergencyContact.all
  end

  # GET /emergency_contacts/1
  # GET /emergency_contacts/1.json
  def show
  end

  # GET /emergency_contacts/new
  def new
    @emergency_contact = EmergencyContact.new
  end

  # GET /emergency_contacts/1/edit
  def edit
  end

  # POST /emergency_contacts
  # POST /emergency_contacts.json
  def create
    @emergency_contact = EmergencyContact.new(emergency_contact_params)

    respond_to do |format|
      if @emergency_contact.save
        format.html { redirect_to @emergency_contact, notice: 'Emergency contact was successfully created.' }
        format.json { render :show, status: :created, location: @emergency_contact }
      else
        format.html { render :new }
        format.json { render json: @emergency_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emergency_contacts/1
  # PATCH/PUT /emergency_contacts/1.json
  def update
    if @emergency_contact.update(emergency_contact_params)
      render json: {data: @emergency_contact, status:'200', msg: 'El contacto de emergencia se actualizó correctamente'}
    else
      render json: {data: nil, status:'500', msg:  @emergency_contact.errors.full_messages}
    end
  end

  # DELETE /emergency_contacts/1
  # DELETE /emergency_contacts/1.json
  def destroy
    @emergency_contact.destroy
    respond_to do |format|
      format.html { redirect_to emergency_contacts_url, notice: 'Emergency contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emergency_contact
      @emergency_contact = EmergencyContact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emergency_contact_params
      params.require(:emergency_contact).permit(:name, :cell_phone, :telephone, :relationship, :student_id, :status)
    end
end

app/helpers/emergency_contacts_helper.rb
module EmergencyContactsHelper
end

app/views/emergency_contacts/_form.html.erb
<%= form_with(model: emergency_contact, local: true) do |form| %>
  <% if emergency_contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(emergency_contact.errors.count, "error") %> prohibited this emergency_contact from being saved:</h2>

      <ul>
      <% emergency_contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :cell_phone %>
    <%= form.text_field :cell_phone %>
  </div>

  <div class="field">
    <%= form.label :telephone %>
    <%= form.text_field :telephone %>
  </div>

  <div class="field">
    <%= form.label :relationship %>
    <%= form.text_field :relationship %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.number_field :student_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/emergency_contacts/edit.html.erb
<h1>Editing Emergency Contact</h1>

<%= render 'form', emergency_contact: @emergency_contact %>

<%= link_to 'Show', @emergency_contact %> |
<%= link_to 'Back', emergency_contacts_path %>

app/views/emergency_contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Emergency Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cell phone</th>
      <th>Telephone</th>
      <th>Relationship</th>
      <th>Student</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emergency_contacts.each do |emergency_contact| %>
      <tr>
        <td><%= emergency_contact.name %></td>
        <td><%= emergency_contact.cell_phone %></td>
        <td><%= emergency_contact.telephone %></td>
        <td><%= emergency_contact.relationship %></td>
        <td><%= emergency_contact.student_id %></td>
        <td><%= emergency_contact.status %></td>
        <td><%= link_to 'Show', emergency_contact %></td>
        <td><%= link_to 'Edit', edit_emergency_contact_path(emergency_contact) %></td>
        <td><%= link_to 'Destroy', emergency_contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Emergency Contact', new_emergency_contact_path %>

app/views/emergency_contacts/new.html.erb
<h1>New Emergency Contact</h1>

<%= render 'form', emergency_contact: @emergency_contact %>

<%= link_to 'Back', emergency_contacts_path %>

app/views/emergency_contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @emergency_contact.name %>
</p>

<p>
  <strong>Cell phone:</strong>
  <%= @emergency_contact.cell_phone %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @emergency_contact.telephone %>
</p>

<p>
  <strong>Relationship:</strong>
  <%= @emergency_contact.relationship %>
</p>

<p>
  <strong>Student:</strong>
  <%= @emergency_contact.student_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @emergency_contact.status %>
</p>

<%= link_to 'Edit', edit_emergency_contact_path(@emergency_contact) %> |
<%= link_to 'Back', emergency_contacts_path %>