config/routes.rb
Rails.application.routes.draw do
  
  resources :modalities
  resources :concerted_qualifications
  resources :concept_payments
  resources :installations
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  devise_for :users, controllers: {sessions: 'user/sessions', registrations: 'user/registrations'}
  root to: 'welcome#index'
  #RESOURCE
  resources :schedules
  resources :time_tables
  resources :type_scolarships
  resources :scolarships
  resources :graduation_institutions
  resources :emergency_contacts
  resources :study_plans
  resources :asignatures
  resources :students, path: "estudiantes"
  resources :departments
  resources :session_modules
  resources :tuitions
  resources :costs
  resources :workplaces
  resources :education_levels
  resources :level_studies
  resources :teachers, :path =>'profesores'
  resources :addresses, :path =>'direcciones'
  resources :level_academics, :path =>'niveles/academicos'
  resources :type_activities, :path =>'tipos/actividad'
  resources :type_costs, :path =>'tipos/costo'
  resources :pay_concepts, :path => 'conceptos/pago'
  resources :type_payments, :path => 'tipos/pago'
  resources :ingresses, :path =>'ingresos'
  resources :cycles, :path =>'ciclos'
  resources :debits, :path =>'adeudos'
  resources :activities, :path =>'actividades'
  resources :module_activities, :path =>'modulos/actividades'
  resources :administrators
  resources :assistants, :path => 'asistentes'
  #GET
  #get '/reporte/alumno', to: 'reports#students'
  get '/registrar', to: 'user#new_user'
  get '/ver/adeudos/actividades/', to: 'debits#get_user_debits', as: 'show_debits'
  get '/usuarios', to: 'user#get_users'
  get '/actividad/registro', to: 'register_user_activity#index' , as: 'register'
  get '/actividad/lista', to: 'register_user_activity#get_activity'
  post '/actividad/registrar/usuario', to: 'register_user_activity#saveUserInActivity'
  post '/pagar/adeudo', to: 'ingresses#add' 
  get '/reporte/inscrito/actividad/:id', to: 'reports#payment_report', as: 'recibo'
  get '/reporte/actividad/:id/inscritos', to: 'reports#assistants_activity_report', as: 'inscritos'
  get '/constancias/actividades/:id', to: 'reports#constancy_ac'
  post '/cargar/materias', to: 'asignatures#charge_asignatures_from_file'
  #POST
  post "/graphql", to: "graphql#execute"
  post '/registrar', to: 'user#create_user'
  post '/docente/documentos/:type', to: 'teachers#upload_files'
  post '/docente/registro/', to: 'teachers#create'
  patch '/docente/actualizar/', to: 'teachers#update'
  get '/reporte/ingresos/:id', to: 'reports#ingress_activity_report'
  get '/reporte/inscripcion/:id', to: 'reports#inscription_report'
  get '/formato/concentrado/:id', to: 'formats#grade_sheets'
  get '/formato/asistencia/:id', to: 'formats#assistant_sheets'
  get '/formato/tira/materias/:id', to: 'formats#schedule_assignment'
  get '/formato/compromiso/pagos/:id', to: 'formats#commitment_payment'
  get '/profesor/:id', to: 'teachers#get_teacher'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/level_study.rb
class LevelStudy < ApplicationRecord
    has_many :assistants
end

app/controllers/level_studies_controller.rb
class LevelStudiesController < ApplicationController
  before_action :set_level_study, only: [:show, :edit, :update, :destroy]

  # GET /level_studies
  # GET /level_studies.json
  def index
    @level_studies = LevelStudy.all
  end

  # GET /level_studies/1
  # GET /level_studies/1.json
  def show
  end

  # GET /level_studies/new
  def new
    @level_study = LevelStudy.new
  end

  # GET /level_studies/1/edit
  def edit
  end

  # POST /level_studies
  # POST /level_studies.json
  def create
    @level_study = LevelStudy.new(level_study_params)

    respond_to do |format|
      if @level_study.save
        format.html { redirect_to @level_study, notice: 'Level study was successfully created.' }
        format.json { render :show, status: :created, location: @level_study }
      else
        format.html { render :new }
        format.json { render json: @level_study.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /level_studies/1
  # PATCH/PUT /level_studies/1.json
  def update
    respond_to do |format|
      if @level_study.update(level_study_params)
        format.html { redirect_to @level_study, notice: 'Level study was successfully updated.' }
        format.json { render :show, status: :ok, location: @level_study }
      else
        format.html { render :edit }
        format.json { render json: @level_study.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /level_studies/1
  # DELETE /level_studies/1.json
  def destroy
    @level_study.destroy
    respond_to do |format|
      format.html { redirect_to level_studies_url, notice: 'Level study was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level_study
      @level_study = LevelStudy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def level_study_params
      params.require(:level_study).permit(:name, :status, :type)
    end
end

app/helpers/level_studies_helper.rb
module LevelStudiesHelper
end

app/views/level_studies/_form.html.erb
<%= form_with(model: level_study, local: true) do |form| %>
  <% if level_study.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(level_study.errors.count, "error") %> prohibited this level_study from being saved:</h2>

      <ul>
      <% level_study.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/level_studies/edit.html.erb
<h1>Editing Level Study</h1>

<%= render 'form', level_study: @level_study %>

<%= link_to 'Show', @level_study %> |
<%= link_to 'Back', level_studies_path %>

app/views/level_studies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Level Studies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @level_studies.each do |level_study| %>
      <tr>
        <td><%= level_study.name %></td>
        <td><%= level_study.status %></td>
        <td><%= level_study.type %></td>
        <td><%= link_to 'Show', level_study %></td>
        <td><%= link_to 'Edit', edit_level_study_path(level_study) %></td>
        <td><%= link_to 'Destroy', level_study, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Level Study', new_level_study_path %>

app/views/level_studies/new.html.erb
<h1>New Level Study</h1>

<%= render 'form', level_study: @level_study %>

<%= link_to 'Back', level_studies_path %>

app/views/level_studies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @level_study.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @level_study.status %>
</p>

<p>
  <strong>Type:</strong>
  <%= @level_study.type %>
</p>

<%= link_to 'Edit', edit_level_study_path(@level_study) %> |
<%= link_to 'Back', level_studies_path %>